platform :ios, '10.0'
use_frameworks!
install! 'cocoapods', :deterministic_uuids => false

source 'git@github.com:applicaster/CocoaPods.git'
source 'https://cdn.cocoapods.org/'

target 'PocketWatchParentGateExample' do
    pod 'PocketWatchParentGate', :path => '../'
end
